### PR TITLE
Cache Minification

### PR DESCRIPTION
**Pull request by zodern**
Uses memory and disk caches to only minify changed files.

To use it, add it to an app with:
```
meteor add zodern:standard-minifier-js@4.0.0-beta.6
```

### CODE REVIEW

**Comment by Floriferous** [comment]
Where are the caches stored? So we can monitor their size on disk.

**Comment by Floriferous** [comment]
Tested this in our repo, but it doesn't seem to be working when you call `meteor build` from outside the meteor app. Or at least there is no significant difference.

EDIT: We use this exact command: `meteor build some/path/. --server-only --architecture os.linux.x86_64`

**Comment by remarcable** [comment]
Hey @zodern, any update on this?

**Comment by zodern** [comment]
@Floriferous The cache is saved in `.meteor/local/plugin-cache/zodern_standard-minifier-js/4.0.0-beta.2`. 

> Tested this in our repo, but it doesn't seem to be working when you call meteor build from outside the meteor app. Or at least there is no significant difference.
> EDIT: We use this exact command: meteor build some/path/. --server-only --architecture os.linux.x86_64

I am not able to reproduce this. Could you please try running with the `METEOR_BABELMINIFIER_CACHE_DEBUG=true` env variable set?

**Comment by zodern** [comment]
> Hey @zodern, any update on this?

It works for many apps, but some people have seen no improvement and I want to find the cause before merging it.

**Comment by zodern** [comment]
The third beta should fix the problems with cache not being used. It also adds an env variable that when set to true disables creating the stats.json: `DISABLE_CLIENT_STATS=true`. `stats.json` is usually only needed when using the bundle visualizer, and can take at least a few seconds to generate.

Try it with
```
meteor add zodern:standard-minifier-js@4.0.0-beta.3
```

The hash Meteor was providing for the file would change even though the file's content and source map were the same. Since those are the only two things that affect the minifier output, it now creates a hash based on only the content and source map.

**Comment by zodern** [comment]
Version 4.0.0 has been released

**Pull request merged**
